// Core Unit Test
import "../src/js/tests/unit/clean.js";
import "../src/js/tests/unit/comments.js";
import "../src/js/tests/unit/editor.js";
import "../src/js/tests/unit/format.js";
import "../src/js/tests/unit/selection.js"
import "../src/js/tests/unit/keys/backspace_br.js";
import "../src/js/tests/unit/keys/backspace_div";
import "../src/js/tests/unit/keys/backspace_i.js";
import "../src/js/tests/unit/keys/backspace_p";
import "../src/js/tests/unit/keys/delete_br.js";
import "../src/js/tests/unit/keys/delete_div.js";
import "../src/js/tests/unit/keys/delete_p.js";
import "../src/js/tests/unit/keys/enter_br.js";
import "../src/js/tests/unit/keys/enter_div.js";
import "../src/js/tests/unit/keys/enter_p.js";
import "../src/js/tests/unit/keys/shift_enter_br.js";
import "../src/js/tests/unit/keys/shift_enter_div.js";
import "../src/js/tests/unit/keys/shift_enter_p.js";
import "../src/js/tests/unit/lists/lists_br.js"
import "../src/js/tests/unit/lists/lists_div.js"
import "../src/js/tests/unit/misc.js";
import "../src/js/tests/unit/misc/invisible_space.js";
import "../src/js/tests/unit/misc/spaces.js";
import "../src/js/tests/unit/paste.js";
import "../src/js/tests/unit/quote/quote_br.js"
import "../src/js/tests/unit/quote/quote_div.js"
import "../src/js/tests/unit/quote/quote_p.js"
import "../src/js/tests/unit/wrap.js";
// import "../src/js/tests/unit/url_regex.js" // 26 tests failing because of regex issue as in master

// Plugins
import "../src/js/modules/core/html.js"
import "../src/js/modules/core/helpers.js"
import "../src/js/plugins/align.js"
import "../src/js/plugins/colors.js"
import "../src/js/plugins/char_counter.js"
import "../src/js/plugins/entities.js";
import "../src/js/plugins/image.js"
import "../src/js/plugins/link.js"
import "../src/js/plugins/lists.js"
import "../src/js/plugins/image_manager.js"
import "../src/js/plugins/inline_style.js"
import "../src/js/plugins/paragraph_format.js"
import "../src/js/plugins/table.js"
import "../src/js/plugins/video.js";
import "../src/js/plugins/word_paste.js"

// Plugins Unit Test
import "../src/js/tests/unit/align.js"
import "../src/js/tests/unit/misc/lists_table.js"
import "../src/js/tests/unit/plugins/colors.js"
import "../src/js/tests/unit/plugins/char_counter.js"
import "../src/js/tests/unit/plugins/entities.js";
import "../src/js/tests/unit/plugins/image.js"
import "../src/js/tests/unit/lists/lists_format.js"
import "../src/js/tests/unit/lists/lists_p.js"
import "../src/js/tests/unit/links/mail_links.js"
import "../src/js/tests/unit/links/inline_styled_links.js"
import "../src/js/tests/unit/imageUpload.js"
import "../src/js/tests/unit/inline_style.js"
import "../src/js/tests/unit/list_format_word"
import "../src/js/tests/unit/paragraph_format.js"
import "../src/js/tests/unit/screensize.js"
import "../src/js/tests/unit/table.js"
import "../src/js/tests/unit/template.js"
import "../src/js/tests/unit/table/delete_column_row.js"
import "../src/js/tests/unit/table/insert_column_row.js"
import "../src/js/tests/unit/table/merge_cells.js"
import "../src/js/tests/unit/table/split_cell.js"
import "../src/js/tests/unit/plugins/video_embedded_regex.js";
