// Plugins
import './plugins/align.js';
import './plugins/char_counter.js'
import './plugins/code_beautifier.js';
import './plugins/code_view.js';
import  './plugins/colors.js'
import './plugins/draggable.js'
import './plugins/edit_in_popup.js';
import './plugins/emoticons.js';
import './plugins/entities.js';
import './plugins/file.js';
import './plugins/files_manager.js'
import './plugins/cryptojs.js'
import './plugins/font_family.js'
import './plugins/font_size.js'
import './plugins/forms.js';
import './plugins/fullscreen.js';
import './plugins/help.js'
import './plugins/image.js'
import './plugins/image_manager.js'
import './plugins/inline_class.js'
import './plugins/inline_style.js'
import './plugins/line_breaker.js'
import './plugins/line_height.js'
import './plugins/link.js'
import './plugins/lists.js'
import './plugins/paragraph_format.js'
import './plugins/paragraph_style.js'
import './plugins/print.js'
import './plugins/quick_insert.js'
import './plugins/quote.js'
import './plugins/save.js'
import './plugins/special_characters.js'
import './plugins/table.js'
import './plugins/url.js'
import './plugins/video.js'
import './plugins/word_paste.js';
